import { writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { parseArgs } from 'node:util'
import { stringify } from 'yaml'
import { aliasTarget, type JsonValue, type UidxDocument } from '@uidx/format'
import { listComponents, listTokens } from '@uidx/agent/core'
import { loadDocs } from './components.js'
import type { Io } from '../cli.js'

/**
 * `uidx export design-md [--out DESIGN.md]`: the design system as a DESIGN.md
 * (Google Labs' format, version alpha) — tokens in YAML front matter, the
 * components' words as prose — for agents and tools that read that file
 * rather than MCP. A portable summary: the identities stay the source.
 */
export async function runDesignMd(argv: string[], io: Io): Promise<number> {
  const { values } = parseArgs({
    args: argv,
    options: { root: { type: 'string' }, out: { type: 'string', default: 'DESIGN.md' } },
  })
  const cwd = io.cwd ?? process.cwd()
  const { root, docs } = await loadDocs(cwd, values.root)
  const text = designMd(docs, String(root.split(/[\\/]/).at(-2) ?? 'Design system'))
  await writeFile(resolve(cwd, values.out!), text)
  io.out(`wrote ${values.out}\n`)
  return 0
}

const dimension = (value: JsonValue): string | undefined =>
  typeof value === 'number' ? `${value}px` : typeof value === 'string' ? value : undefined

/** `color#accent` → the DESIGN.md token path it was exported under. */
function tokenPath(address: string, group: string): string {
  return `{${group}.${address.replace('#', '-')}}`
}

export function designMd(docs: ReadonlyMap<string, UidxDocument>, name: string): string {
  const colors: Record<string, string> = {}
  const rounded: Record<string, string> = {}
  const spacing: Record<string, string> = {}
  const typography: Record<string, Record<string, string>> = {}
  const groupOf = new Map<string, string>()
  for (const token of listTokens(docs)) {
    const key = token.token.replace('#', '-')
    const collection = token.token.split('#')[0]!
    if (token.type === 'COLOR' && typeof token.value === 'string') {
      colors[key] = token.value
      groupOf.set(token.token, 'colors')
    } else if (token.type === 'FLOAT') {
      const value = dimension(token.value)
      if (value === undefined) continue
      if (/radius|round|corner/i.test(collection)) {
        rounded[key] = value
        groupOf.set(token.token, 'rounded')
      } else if (/space|spacing|gap|size/i.test(collection)) {
        spacing[key] = value
        groupOf.set(token.token, 'spacing')
      } else if (/type|font|text/i.test(collection)) {
        typography[key] = { fontSize: value }
        groupOf.set(token.token, 'typography')
      }
    }
  }
  const ref = (value: JsonValue | undefined): string | undefined => {
    if (value === undefined) return undefined
    const target = aliasTarget(value)
    if (target && groupOf.has(target)) return tokenPath(target, groupOf.get(target)!)
    return dimension(value)
  }

  const components: Record<string, Record<string, string>> = {}
  const prose: string[] = []
  for (const summary of listComponents(docs)) {
    const doc = docs.get(summary.file)!
    const node = doc.tree.children.find((child) => child.name === summary.name)!
    const text = node.children.find((child) => child.element === 'Text')
    const base: Record<string, string | undefined> = {
      backgroundColor: ref(node.attrs.fills?.value),
      textColor: ref(text?.attrs.fills?.value),
      rounded: ref(node.attrs.cornerRadius?.value),
      padding: ref(node.attrs.paddingLeft?.value),
      height: ref(node.attrs.height?.value),
      width: ref(node.attrs.width?.value),
    }
    const slug = summary.name.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase()
    components[slug] = clean(base)
    for (const row of doc.spec?.styles ?? []) {
      const suffix = Object.values(row.keys).join('-')
      const entry = clean({
        backgroundColor: ref(row.values.root?.fills),
        textColor: ref(text ? row.values[text.name]?.fills : undefined),
        rounded: ref(row.values.root?.cornerRadius),
        padding: ref(row.values.root?.paddingLeft),
      })
      if (Object.keys(entry).length) components[`${slug}-${suffix}`] = entry
    }
    const rules = (doc.spec?.behavior ?? []).map((rule) => `  - ${rule.id}: ${rule.text}`)
    const props = (doc.spec?.contract?.props ?? []).map(
      (prop) => `\`${prop.name}\` (${prop.type ?? 'unknown'})`,
    )
    prose.push(
      `### ${summary.name}`,
      '',
      summary.summary || 'No description yet.',
      '',
      ...(props.length ? [`Props: ${props.join(', ')}.`, ''] : []),
      ...(rules.length ? ['Behaviour:', '', ...rules, ''] : []),
    )
  }

  const front = stringify(
    clean({
      version: 'alpha',
      name,
      description: `Generated by uidx from ${docs.size} design files; the .uidx identities are the source.`,
      colors,
      typography,
      rounded,
      spacing,
      components,
    }),
  )
  const colorLines = Object.entries(colors).map(([key, value]) => `- **${key} (${value})**`)
  return `---\n${front}---\n\n## Overview\n\nThe ${name} design system, written as uidx identities: every component has a contract, state styles and behaviour rules, and code is generated from them. Use its components and tokens; never hard-code a value a token names.\n\n## Colors\n\n${colorLines.join('\n')}\n\n## Components\n\n${prose.join('\n')}\n`
}

function clean<T extends Record<string, unknown>>(value: T): Record<string, never> & T {
  return Object.fromEntries(
    Object.entries(value).filter(
      ([, v]) => v !== undefined && !(typeof v === 'object' && v && !Object.keys(v).length),
    ),
  ) as Record<string, never> & T
}
