import { mkdir, writeFile } from 'node:fs/promises'
import { join, resolve } from 'node:path'
import { parseArgs } from 'node:util'
import type { UidxDocument } from '@uidx/format'
import { listComponents, listTokens, renderToPng } from '@uidx/agent/core'
import { loadDocs } from './components.js'
import type { Io } from '../cli.js'

/**
 * `uidx share --out <dir>`: the document as a static, read-only site — every
 * page drawn as the canvas draws it, every component's documentation, every
 * token — for the people who review a design system without running it: a
 * product owner, a stakeholder, a pull request's preview deployment. No
 * server and no account; any static host serves it.
 */
export async function runShare(argv: string[], io: Io): Promise<number> {
  const { values } = parseArgs({
    args: argv,
    options: { root: { type: 'string' }, out: { type: 'string', default: 'uidx-site' } },
  })
  const cwd = io.cwd ?? process.cwd()
  const { root, docs } = await loadDocs(cwd, values.root)
  const out = resolve(cwd, values.out!)
  await mkdir(join(out, 'pages'), { recursive: true })

  const pictures = new Map<string, string>()
  for (const [file, doc] of docs) {
    if (doc.tree.element !== 'Page') continue
    const name = `pages/${file.replace(/\.uidx$/, '').replace(/[\\/]/g, '__')}.png`
    try {
      await writeFile(join(out, name), await renderToPng({ docs, file, scale: 1 }))
      pictures.set(file, name)
    } catch (error) {
      io.err(`${file}: not drawn — ${(error as Error).message}\n`)
    }
  }

  const components = listComponents(docs)
  const title = String(root.split(/[\\/]/).at(-2) ?? 'Design system')
  const sections = components.map((component) => componentSection(component.name, docs, pictures))
  const tokens = listTokens(docs)
  const html = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escape(title)} — design system</title>
<style>
:root { color-scheme: light dark; --bg: #fff; --text: #16181d; --dim: #5d6370; --line: #e3e6ec; --panel: #f6f7f9; }
@media (prefers-color-scheme: dark) { :root { --bg: #16181d; --text: #eef0f4; --dim: #a0a6b2; --line: #2c3038; --panel: #1f2229; } }
body { margin: 0; font: 14px/1.6 Inter, system-ui, sans-serif; background: var(--bg); color: var(--text); }
main { max-width: 1040px; margin: 0 auto; padding: 32px 20px 80px; }
nav a { margin-right: 12px; color: inherit; }
h1 { font-size: 28px; margin: 0 0 4px; } h2 { margin: 48px 0 8px; } .dim { color: var(--dim); }
figure { margin: 16px 0; padding: 16px; background: var(--panel); border: 1px solid var(--line); border-radius: 8px; overflow: auto; }
figure img { max-width: 100%; }
table { width: 100%; border-collapse: collapse; font-size: 13px; }
th, td { text-align: left; border-bottom: 1px solid var(--line); padding: 6px 8px; vertical-align: top; }
code { font: 12px ui-monospace, monospace; } .swatch { display: inline-block; width: 14px; height: 14px; border-radius: 3px; border: 1px solid var(--line); vertical-align: middle; margin-right: 6px; }
</style></head>
<body><main>
<h1>${escape(title)}</h1>
<p class="dim">${components.length} components · ${tokens.length} tokens · generated by <code>uidx share</code>, read-only</p>
<nav>${components.map((c) => `<a href="#${anchor(c.name)}">${escape(c.name)}</a>`).join('')}<a href="#tokens">Tokens</a></nav>
${sections.join('\n')}
<h2 id="tokens">Tokens</h2>
<table><thead><tr><th>Token</th><th>Value</th><th>CSS</th><th>Description</th></tr></thead><tbody>
${tokens
  .map(
    (token) =>
      `<tr><td><code>${escape(token.token)}</code></td><td>${
        token.type === 'COLOR' && typeof token.value === 'string'
          ? `<span class="swatch" style="background:${escape(token.value)}"></span>`
          : ''
      }<code>${escape(JSON.stringify(token.value))}</code></td><td><code>${escape(token.css)}</code></td><td>${escape(token.description)}</td></tr>`,
  )
  .join('\n')}
</tbody></table>
</main></body></html>
`
  await writeFile(join(out, 'index.html'), html)
  io.out(
    `wrote ${values.out}/index.html with ${components.length} components and ${pictures.size} page pictures\n`,
  )
  return 0
}

function componentSection(
  name: string,
  docs: ReadonlyMap<string, UidxDocument>,
  pictures: ReadonlyMap<string, string>,
): string {
  const [file, doc] = [...docs].find(([, d]) => d.tree.children.some((n) => n.name === name))!
  const contract = doc.spec?.contract
  const intent = doc.intent.raw.replace(/^#{1,6}\s.*$/gm, '').trim()
  const picture = pictures.get(file)
  const rows = (contract?.props ?? [])
    .map(
      (prop) =>
        `<tr><td><code>${escape(prop.name)}</code>${prop.visual ? ' <span class="dim">visual</span>' : ''}</td><td><code>${escape(prop.type ?? '')}</code></td><td><code>${escape(prop.default === undefined ? '' : JSON.stringify(prop.default))}</code></td><td>${escape(prop.description)}</td></tr>`,
    )
    .join('\n')
  const events = (contract?.events ?? [])
    .map((event) => `<li><code>${escape(event.name)}</code> — ${escape(event.description)}</li>`)
    .join('')
  const behavior = (doc.spec?.behavior ?? [])
    .map((rule) => `<li><code>${escape(rule.id)}</code> — ${escape(rule.text)}</li>`)
    .join('')
  return `<h2 id="${anchor(name)}">${escape(name)}</h2>
${intent ? `<p>${escape(intent).replace(/\n\n+/g, '</p><p>')}</p>` : ''}
${picture ? `<figure><img src="${picture}" alt="${escape(name)} as designed"></figure>` : ''}
${rows ? `<table><thead><tr><th>Prop</th><th>Type</th><th>Default</th><th>Description</th></tr></thead><tbody>${rows}</tbody></table>` : ''}
${events ? `<h3>Events</h3><ul>${events}</ul>` : ''}
${behavior ? `<h3>Behaviour</h3><ul>${behavior}</ul>` : ''}`
}

function anchor(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '-')
}

function escape(text: string): string {
  return text.replace(
    /[&<>"]/g,
    (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[c]!,
  )
}
