import js from '@eslint/js'
import tseslint from 'typescript-eslint'
import vue from 'eslint-plugin-vue'
import prettier from 'eslint-config-prettier'
import globals from 'globals'

/**
 * Flat config for the whole workspace.
 *
 * Deliberately the untyped `recommended` set rather than `recommendedTypeChecked`.
 * The typed rules need a program per package and are the slowest thing that
 * could sit in the CI gate; more to the point, the rules that would earn that
 * cost here (`no-floating-promises`, `no-unnecessary-condition`) argue with a
 * codebase that uses `void promise` deliberately and runs `strict` with
 * `noUncheckedIndexedAccess` already. Worth revisiting once packages build
 * (their `tsconfig`s are what a typed config would point at), not before.
 *
 * Formatting is Prettier's, not ESLint's — `eslint-config-prettier` last turns
 * off every stylistic rule so the two can never disagree.
 */
export default tseslint.config(
  {
    ignores: [
      '**/dist/**',
      '**/.build/**',
      '**/node_modules/**',
      'packages/viewer/public/**',
      // Generated by `pnpm build:cli`, and checked by `binary.test.ts` instead.
      'packages/cli/dist/**',
      // Git worktrees live here. They are whole checkouts of this repo, so
      // linting them reports every file twice — and reports stale copies of
      // code that has since been fixed on main, from a directory that is
      // gitignored scratch. `pnpm lint` from the repo root fails on somebody
      // else's branch without this.
      '.claude/**',
      '.uidx/**',
      '.uidx-agent/**',
      '.superpowers/**',
      '.pnpm-store/**',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,
  ...vue.configs['flat/recommended'],

  {
    files: ['**/*.vue'],
    languageOptions: {
      parserOptions: { parser: tseslint.parser },
    },
  },

  {
    rules: {
      // `_`-prefixed parameters are how this codebase marks an argument it must
      // accept and deliberately ignores — a host font loader that takes a family
      // it does not use, for one.
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrors: 'none' },
      ],
      // The mdast tree is untyped by its own libraries; `parse.ts` says so at the
      // top and narrows at the boundary. Flagging it repo-wide would be noise.
      '@typescript-eslint/no-explicit-any': 'warn',
      // A CLI's whole output is console; a viewer's should not be.
      'no-console': 'error',
    },
  },

  // Everything outside the viewer runs in Node.
  {
    files: [
      'packages/cli/**/*.ts',
      'packages/server/**/*.ts',
      'packages/format/**/*.ts',
      'packages/schema/**/*.ts',
      '**/scripts/**/*.mjs',
      '**/test/**/*.ts',
      '*.config.ts',
      'eslint.config.js',
    ],
    languageOptions: { globals: globals.node },
  },
  {
    files: ['packages/viewer/src/**/*.{ts,vue}'],
    languageOptions: { globals: globals.browser },
  },

  {
    // A script's whole output is a report to the terminal. The glob reaches
    // into packages so a script can live beside the code it drives rather
    // than only at the repo root.
    files: ['packages/cli/**/*.ts', '**/scripts/**/*.mjs'],
    rules: { 'no-console': 'off' },
  },
  {
    // The bin entry's whole output is a startup banner to the terminal, same
    // reasoning as the cli package above — the rest of the agent package is
    // library code and keeps the rule.
    files: ['packages/agent/src/server/main.ts'],
    rules: { 'no-console': 'off' },
  },

  {
    files: ['**/test/**/*.ts', '**/*.test.ts'],
    rules: {
      // Timing tests report their measurements; a figure nobody can see is not
      // a measurement.
      'no-console': 'off',
      '@typescript-eslint/no-non-null-assertion': 'off',
      // A test that mounts three throwaway components to exercise an error
      // boundary is doing the right thing; the rule is about source files.
      'vue/one-component-per-file': 'off',
      'vue/order-in-components': 'off',
    },
  },

  prettier,
)
