import { describe, expect, it } from 'vitest'
import { parseOrThrow } from '@uidx/format'

import { appLintContext, lintAppSource } from '../src/core/app-lint.js'

const docs = new Map([
  [
    'tokens.uidx',
    parseOrThrow(`---
id: tokens
---

## Visual Contract

<Tokens>
  <Collection name="color">
    <Variable name="accent" type="COLOR" value={{ r: 0, g: 0.4, b: 1, a: 1 }} />
  </Collection>
</Tokens>
`),
  ],
  [
    'button.uidx',
    parseOrThrow(`---
id: button
---

## Visual Contract

<Page>
  <Component name="Button" width={80} height={32} />
</Page>
`),
  ],
])

describe('lintAppSource', () => {
  const context = appLintContext(docs)

  it('names the token a colour literal equals, in hex or rgb', () => {
    const found = lintAppSource(
      'a.css',
      '.x { color: #0066FF; border-color: rgb(0, 102, 255); }',
      context,
    )
    expect(found.map((f) => [f.rule, f.column])).toEqual([
      ['token-literal', 13],
      ['token-literal', 36],
    ])
    expect(found[0]!.message).toContain('color#accent (var(--color-accent))')
  })

  it('names the component a raw element stands for, in markup only', () => {
    expect(lintAppSource('a.tsx', 'return <button>Go</button>', context)[0]?.message).toBe(
      '<button> has a design-system component: use <Button>',
    )
    expect(lintAppSource('a.ts', "const tag = '<button>'", context)).toEqual([])
  })

  it('leaves generated code and unrelated colours alone', () => {
    expect(
      lintAppSource(
        'B.tsx',
        '// Button — generated by uidx codegen\n<button style="color:#0066ff" />',
        context,
      ),
    ).toEqual([])
    expect(lintAppSource('a.css', '.x { color: #123456 }', context)).toEqual([])
  })
})
