import type { UidxDocument } from '@uidx/format'
import { listComponents, listTokens } from './design-system.js'

/**
 * The design system's rules applied to application code (`uidx lint`): the
 * checks that keep AI-written UI on-system, deterministic and with no model
 * in the loop.
 *
 * - A colour literal that equals a token's value — the token's CSS variable
 *   should be there instead.
 * - A raw element a design-system component stands for — `<button>` where
 *   the system has a Button.
 *
 * Generated code is skipped: it says so in its first line.
 */
export interface AppFinding {
  file: string
  line: number
  column: number
  rule: 'token-literal' | 'raw-element'
  message: string
}

export interface AppLintContext {
  /** Lower-cased colour → the tokens that resolve to it. */
  colours: Map<string, string[]>
  /** Raw tag → the component that replaces it. */
  elements: Map<string, string>
}

/** Which HTML element a component with this name stands in for, by convention. */
const STANDS_FOR: Record<string, string> = {
  button: 'button',
  checkbox: 'input type="checkbox"',
  radio: 'input type="radio"',
  textinput: 'input',
  input: 'input',
  select: 'select',
  textarea: 'textarea',
  link: 'a',
  dialog: 'dialog',
}

export function appLintContext(docs: ReadonlyMap<string, UidxDocument>): AppLintContext {
  const colours = new Map<string, string[]>()
  for (const row of listTokens(docs)) {
    if (row.type !== 'COLOR' || typeof row.value !== 'string') continue
    const key = row.value.toLowerCase()
    colours.set(key, [...(colours.get(key) ?? []), `${row.token} (${row.css})`])
  }
  const elements = new Map<string, string>()
  for (const component of listComponents(docs)) {
    const tag = STANDS_FOR[component.name.toLowerCase()]
    if (tag && !elements.has(tag)) elements.set(tag, component.name)
  }
  return { colours, elements }
}

const GENERATED = /generated by uidx codegen/
const HEX = /#(?:[0-9a-fA-F]{8}|[0-9a-fA-F]{6}|[0-9a-fA-F]{3})\b/g
const RGB = /rgba?\(\s*(\d{1,3})\s*,\s*(\d{1,3})\s*,\s*(\d{1,3})\s*(?:,\s*(1|1\.0+))?\s*\)/g

function normaliseHex(hex: string): string {
  const digits = hex.slice(1).toLowerCase()
  if (digits.length === 3) return `#${[...digits].map((d) => d + d).join('')}`
  if (digits.length === 8 && digits.endsWith('ff')) return `#${digits.slice(0, 6)}`
  return `#${digits}`
}

export function lintAppSource(file: string, text: string, context: AppLintContext): AppFinding[] {
  if (GENERATED.test(text.slice(0, 400))) return []
  const findings: AppFinding[] = []
  const lines = text.split('\n')
  const isMarkup = /\.(tsx|jsx|vue|svelte|html|astro)$/.test(file)
  lines.forEach((line, at) => {
    const push = (column: number, rule: AppFinding['rule'], message: string) =>
      findings.push({ file, line: at + 1, column: column + 1, rule, message })
    for (const match of line.matchAll(HEX)) {
      const tokens = context.colours.get(normaliseHex(match[0]))
      if (tokens)
        push(match.index, 'token-literal', `${match[0]} is ${tokens.join(', ')}; use the token`)
    }
    for (const match of line.matchAll(RGB)) {
      const hex = `#${[match[1], match[2], match[3]]
        .map((c) => Number(c).toString(16).padStart(2, '0'))
        .join('')}`
      const tokens = context.colours.get(hex)
      if (tokens)
        push(match.index, 'token-literal', `${match[0]} is ${tokens.join(', ')}; use the token`)
    }
    if (!isMarkup) return
    for (const [tag, component] of context.elements) {
      const [name, ...attrs] = tag.split(' ')
      const pattern = new RegExp(
        `<${name}\\b${attrs.length ? `[^>]*${escapeRegex(attrs.join(' '))}` : ''}`,
      )
      const match = pattern.exec(line)
      if (match)
        push(
          match.index,
          'raw-element',
          `<${tag}> has a design-system component: use <${component}>`,
        )
    }
  })
  return findings
}

function escapeRegex(text: string): string {
  return text.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}
