import type { JsonValue, UidxNode } from '@uidx/format'
import { specBindings, STATE_AXIS, styleTarget } from '@uidx/schema/design-system'
import { cssDeclarations, cssRule, type CssKind } from './css.js'
import { boundPath, boundProp, type ComponentModel } from './model.js'

/**
 * The HTML/CSS target (ADR 0017 §3): one stylesheet per component, keyed by
 * the headless root's attributes and states, and one markup fragment
 * showing the anatomy with sample content.
 */

export interface HtmlContext {
  /** Every component of the document set, by name — for instances and repeats. */
  components: Map<string, ComponentModel>
}

/** How a state of the contract is selected in CSS. */
export function stateSelector(state: string): string {
  switch (state) {
    case 'hover':
      return ':hover'
    case 'focus':
      return ':focus-visible'
    case 'active':
    case 'pressed':
      return ':active'
    default:
      return `[${state}]`
  }
}

const VOID_ATTRS = new Set([
  'name',
  'part',
  'characters',
  'vectorPaths',
  'implements',
  'slot',
  'count',
  'component',
  'props',
  'overrides',
  'status',
  'version',
  'modes',
  'rootFontSize',
])

function attrValues(node: UidxNode): Record<string, JsonValue> {
  const out: Record<string, JsonValue> = {}
  for (const [name, attr] of Object.entries(node.attrs)) {
    if (VOID_ATTRS.has(name)) continue
    out[name] = attr.value
  }
  return out
}

/** A text's fill is its colour; so is a vector's, whose paths use `currentColor`. */
function kindOf(node: UidxNode): CssKind {
  return node.element === 'Text' || node.element === 'Vector' ? 'text' : 'container'
}

/** The selector for a node inside the component, given the root's selector. */
function selectorFor(model: ComponentModel, node: UidxNode, root: string): string {
  if (node === model.node) return root
  const part = model.partOf.get(node)
  if (part !== undefined) {
    const info = model.parts.find((entry) => entry.name === part)!
    return `${root} ${info.tag}`
  }
  if (node.element === 'Slot') return `${root} [data-slot="${node.name}"]`
  return `${root} [data-node="${node.name}"]`
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

/** The stylesheet: the base tree, then the styles table as state and attribute rules. */
export function emitCss(model: ComponentModel): string {
  const root = model.tag ?? `.${model.stem}`
  const rules: string[] = [
    `/* ${model.name} — generated by uidx codegen; edit the .uidx file instead. */\n`,
  ]
  const declared = new Set<string>()

  const walk = (node: UidxNode): void => {
    if (node.element === 'Repeat') {
      for (const child of node.children) walk(child)
      return
    }
    if (node.element === 'Instance') return
    // A composition has no element of its own to style; its instance's
    // stylesheet is the one that applies.
    if (node === model.node && model.composes) return
    const selector = selectorFor(model, node, root)
    const declarations = cssDeclarations(attrValues(node), kindOf(node))
    if (node === model.node && !declarations.display && node.attrs.layoutMode === undefined) {
      // A component is a frame (ADR 0008): its children stack unless it says otherwise.
      declarations.display = 'inline-flex'
      declarations['flex-direction'] = 'column'
    }
    if (node.element === 'Slot' && !declarations.display) declarations.display = 'contents'
    if (Object.keys(declarations).length) {
      rules.push(cssRule(selector, declarations))
      declared.add(selector)
    }
    for (const child of node.children) walk(child)
  }
  walk(model.node)

  for (const row of model.spec?.styles ?? []) {
    let scoped = root
    for (const [axis, value] of Object.entries(row.keys)) {
      scoped += axis === STATE_AXIS ? stateSelector(value) : `[${axis}="${value}"]`
    }
    for (const [part, props] of Object.entries(row.values)) {
      const info = part === 'root' ? undefined : model.parts.find((entry) => entry.name === part)
      // A row targets the root, a part, or one of the design's own nodes by name.
      const target = part === 'root' ? model.node : (info?.node ?? styleTarget(model.node, part))
      const selector =
        part === 'root'
          ? scoped
          : info
            ? `${scoped} ${info.tag}`
            : `${scoped} [data-node="${part}"]`
      rules.push(cssRule(selector, cssDeclarations(props, target ? kindOf(target) : 'container')))
    }
  }
  return rules.filter(Boolean).join('\n')
}

/** Sample text for a node whose `characters` binds a prop or a model field. */
function sampleText(
  model: ComponentModel,
  node: UidxNode,
  samples: Map<string, JsonValue>,
): string {
  const characters = node.attrs.characters?.value
  if (typeof characters !== 'string') return ''
  const prop = boundProp(model, characters)
  if (prop) {
    const value = samples.get(prop.name) ?? prop.default
    if (value !== undefined && value !== null) return String(value)
    // No sample and no default: the prop's name, as a person would write it.
    return prop.name.replace(/([a-z])([A-Z])/g, '$1 $2').replace(/^./, (c) => c.toUpperCase())
  }
  const path = boundPath(model, characters)
  if (path) {
    const value = samples.get(path.join('.'))
    return value === undefined || value === null ? '' : String(value)
  }
  return characters.startsWith('{') ? '' : characters
}

function markup(
  model: ComponentModel,
  node: UidxNode,
  ctx: HtmlContext,
  samples: Map<string, JsonValue>,
  depth: number,
  /** Which sample an instance inside a repeat shows (ADR 0015 §2). */
  index = 0,
  /** What the consuming page put in this component's slots (ADR 0007 §2), already rendered. */
  fills: ReadonlyMap<string, string[]> = new Map(),
): string[] {
  const pad = '  '.repeat(depth)
  const part = model.partOf.get(node)
  const info = part === undefined ? undefined : model.parts.find((entry) => entry.name === part)
  const children = (): string[] =>
    node.children.flatMap((child) => markup(model, child, ctx, samples, depth + 1, index, fills))

  switch (node.element) {
    case 'Repeat': {
      const count = typeof node.attrs.count?.value === 'number' ? node.attrs.count.value : 0
      const child = node.children[0]
      if (!child) return []
      const lines: string[] = []
      for (let n = 0; n < count; n++) {
        lines.push(...markup(model, child, ctx, specBindings(model.spec, n), depth, n))
      }
      return lines
    }
    case 'Instance': {
      const name = node.attrs.component?.value
      const target = typeof name === 'string' ? ctx.components.get(name) : undefined
      // The component's own anatomy with its samples at this index — the
      // markup a page would hold, not a bare tag — and this page's fills in
      // its slots, rendered here, where their bindings mean this page's.
      if (!target) return [`${pad}<div data-instance="${escapeHtml(String(name ?? ''))}"></div>`]
      const filled = new Map<string, string[]>()
      for (const fill of node.children) {
        if (fill.element !== 'Slot') continue
        filled.set(
          fill.name,
          fill.children.flatMap((child) =>
            markup(model, child, ctx, samples, depth + 2, index, fills),
          ),
        )
      }
      // What this page passes lies over the target's own samples: a `{label}`
      // is this page's prop, resolved in *this* page's samples (ADR 0017 §3),
      // a literal is a literal.
      const passed = new Map(specBindings(target.spec, index))
      const declared = node.attrs.props?.value
      if (declared && typeof declared === 'object' && !Array.isArray(declared)) {
        for (const [key, value] of Object.entries(declared as Record<string, JsonValue>)) {
          const own = boundProp(model, value)
          const resolved = own ? samples.get(own.name) : value
          if (resolved !== undefined && resolved !== null) passed.set(key, resolved)
        }
      }
      return markup(target, target.node, ctx, passed, depth, index, filled)
    }
    case 'Slot': {
      const fill = fills.get(node.name)
      const inner =
        fill ?? (node.children.length ? children() : [`${pad}  ${escapeHtml(node.name)}`])
      return [`${pad}<span data-slot="${node.name}">`, ...inner, `${pad}</span>`]
    }
    case 'Text': {
      const tag = info?.tag ?? 'span'
      const open = info ? `<${tag}>` : `<span data-node="${node.name}">`
      const close = info ? `</${tag}>` : '</span>'
      return [`${pad}${open}${escapeHtml(sampleText(model, node, samples))}${close}`]
    }
    case 'Vector': {
      const width = typeof node.attrs.width?.value === 'number' ? node.attrs.width.value : 16
      const height = typeof node.attrs.height?.value === 'number' ? node.attrs.height.value : 16
      const paths = Array.isArray(node.attrs.vectorPaths?.value)
        ? (node.attrs.vectorPaths.value as JsonValue[])
        : []
      const d = paths
        .map((entry) =>
          entry && typeof entry === 'object' && !Array.isArray(entry)
            ? (entry as Record<string, JsonValue>).data
            : undefined,
        )
        .filter((data): data is string => typeof data === 'string')
      const svg = `<svg viewBox="0 0 ${width} ${height}" width="${width}" height="${height}" aria-hidden="true">${d.map((data) => `<path d="${escapeHtml(data)}" fill="currentColor" />`).join('')}</svg>`
      if (info) return [`${pad}<${info.tag}>${svg}</${info.tag}>`]
      return [`${pad}<span data-node="${node.name}">${svg}</span>`]
    }
    default: {
      // Frame, Rectangle, Ellipse — and the component itself.
      if (node === model.node && model.composes)
        return markup(model, model.composes, ctx, samples, depth, index, fills)
      if (node === model.node) {
        const tag = model.tag ?? 'div'
        const attrs = model.tag ? '' : ` class="${model.stem}"`
        return [`${pad}<${tag}${attrs}>`, ...children(), `${pad}</${tag}>`]
      }
      const tag = info?.tag ?? 'div'
      const open = info ? `<${tag}>` : `<div data-node="${node.name}">`
      const close = info ? `</${tag}>` : '</div>'
      return [`${pad}${open}`, ...children(), `${pad}${close}`]
    }
  }
}

/** The anatomy as markup with sample content: what a consumer's page holds. */
export function emitHtml(model: ComponentModel, ctx: HtmlContext): string {
  return `<!-- ${model.name} — generated by uidx codegen; edit the .uidx file instead. -->\n${markup(model, model.node, ctx, model.samples, 0).join('\n')}\n`
}
