import {
  aliasTarget,
  listProps,
  type FieldSpec,
  type JsonValue,
  type PropSpec,
  type UidxNode,
} from '@uidx/format'
import {
  INSTANCE_BOX_HOOKS,
  modelOfType,
  type ModelIndex,
  type RepeatScope,
} from '@uidx/schema/design-system'
import { INSTANCE_BOX_SHORTHANDS } from '@uidx/schema/instance-box'
import {
  attributeName,
  boundPath,
  boundProp,
  eventName,
  parentOf,
  pascal,
  repeatFor,
  type ComponentModel,
  type RepeatInfo,
  vectorPaint,
} from './model.js'
import { boxOf, instanceInlineStyle, slotsWithin } from './html.js'
import type { ReactBinding } from './react-adapter.js'

/**
 * The React target (ADR 0017 §3): one component per identity, wrapping the
 * headless root. Props and events come from the contract; slots are the
 * render-prop answer — a plain slot is a `ReactNode` prop, a repeating slot
 * is `items` plus `renderItem` generic over the model; parts with consumer
 * text are compound sub-components. Behaviour and accessibility come from the
 * custom element at runtime; appearance from the generated stylesheet.
 */

export interface ReactContext {
  components: Map<string, ComponentModel>
  /**
   * Components rendered onto an existing React library (`codegen.react`), by
   * name. Their adapters take the contract's props and nothing else, so a use
   * that restyles one has no `style` to say it in (ADR 0018 §6).
   */
  adapters?: ReadonlyMap<string, ReactBinding>
  /** Told of each such use, so the generator can say the library's own look is drawn there. */
  warn?: (node: UidxNode, message: string) => void
}

const HEADER = (name: string) =>
  `// ${name} — generated by uidx codegen from its .uidx file. Do not edit; change the file.\n`

/** A contract type string as TypeScript, with model names resolved (ADR 0015 §2). */
export function tsType(model: ComponentModel, type: string | undefined): string {
  return typeAgainst(type, model.spec, model.models)
}

function typeAgainst(
  type: string | undefined,
  spec: ComponentModel['spec'],
  models: ModelIndex,
): string {
  if (!type) return 'unknown'
  const found = modelOfType(type, spec, models)
  if (found) return found.list ? `${pascal(found.model.name)}[]` : pascal(found.model.name)
  const array = type.endsWith('[]')
  const base = array ? type.slice(0, -2) : type
  const inner = base === 'image' || base === 'date' ? 'string' : base
  return array ? `${inner}[]` : inner
}

function fieldType(models: ModelIndex, field: FieldSpec): string {
  return typeAgainst(field.type, undefined, models)
}

/** `models.ts`: one interface per model, fields documented from the file. */
export function emitModels(models: ModelIndex): string {
  const lines = [HEADER('Models'), '']
  for (const model of models.values()) {
    if (model.description) lines.push(`/** ${model.description} */`)
    lines.push(`export interface ${pascal(model.name)} {`)
    for (const field of model.fields) {
      lines.push(`  /** ${field.description} */`)
      lines.push(`  ${field.name}${field.optional ? '?' : ''}: ${fieldType(models, field)}`)
    }
    lines.push('}', '')
  }
  // No models is still a module, so `index.ts` may re-export it.
  if (models.size === 0) lines.push('export {}')
  return `${lines.join('\n')}\n`
}

/** `runtime.ts`: the one hook every generated component uses for events. */
export function emitRuntime(): string {
  return `${HEADER('Runtime')}
import { useEffect, type RefObject } from 'react'

/**
 * Subscribes to a custom element's event and hands the handler its detail.
 * The element owns the behaviour; React only listens.
 */
export function useElementEvent<T>(
  ref: RefObject<HTMLElement | null>,
  type: string,
  handler: ((detail: T) => void) | undefined,
): void {
  useEffect(() => {
    const element = ref.current
    if (!element || !handler) return
    const listener = (event: Event) => handler((event as CustomEvent<T>).detail)
    element.addEventListener(type, listener)
    return () => element.removeEventListener(type, listener)
  }, [ref, type, handler])
}
`
}

/** `elements.d.ts`: the custom elements as JSX intrinsics, attributes open. */
export function emitElementTypes(tags: readonly string[]): string {
  const entries = [...new Set(tags)]
    .sort()
    .map(
      (tag) =>
        `      '${tag}': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> &\n        Record<string, unknown>`,
    )
  return `${HEADER('Elements')}
import type React from 'react'

declare module 'react' {
  namespace JSX {
    interface IntrinsicElements {
${entries.join('\n')}
    }
  }
}

export {}
`
}

export function emitIndex(models: readonly ComponentModel[]): string {
  const lines = [HEADER('Index'), '']
  for (const model of models) lines.push(`export * from './${model.identifier}'`)
  lines.push(`export * from './models'`)
  return `${lines.join('\n')}\n`
}

/* --------------------------------------------------------------- one component */

interface PropLine {
  name: string
  type: string
  optional: boolean
  doc: string
}

function jsxText(text: string): string {
  return text.replace(/[{}<>]/g, (c) => `{'${c}'}`)
}

function svgFor(node: UidxNode): string {
  const width = typeof node.attrs.width?.value === 'number' ? node.attrs.width.value : 16
  const height = typeof node.attrs.height?.value === 'number' ? node.attrs.height.value : 16
  const paths = Array.isArray(node.attrs.vectorPaths?.value)
    ? (node.attrs.vectorPaths.value as JsonValue[])
    : []
  const d = paths
    .map((entry) =>
      entry && typeof entry === 'object' && !Array.isArray(entry)
        ? (entry as Record<string, JsonValue>).data
        : undefined,
    )
    .filter((data): data is string => typeof data === 'string')
  const paint = vectorPaint(node)
    .replace(/stroke-width="/g, 'strokeWidth="')
    .replace(/stroke-linecap="/g, 'strokeLinecap="')
    .replace(/stroke-linejoin="/g, 'strokeLinejoin="')
  return `<svg viewBox="0 0 ${width} ${height}" width={${width}} height={${height}} aria-hidden="true">${d.map((data) => `<path d="${data}" ${paint} />`).join('')}</svg>`
}

/** `renderOption` for a repeating slot named `option` (ADR 0017 §2). */
/** `{child}` or `{child.owner}` inside a repeat: the item, or a field of it, as a JS path. */
function itemAlias(value: JsonValue, scopes: readonly RepeatScope[]): string | null {
  if (typeof value !== 'string') return null
  const target = aliasTarget(value)
  if (target === null || target.includes('#')) return null
  const head = target.split('.')[0]!
  return scopes.some((scope) => scope.as === head) ? target : null
}

const renderPropName = (repeat: RepeatInfo): string => `render${pascal(repeat.node.name)}`

/** The JSX expression a bound `characters` renders: a prop, a model path, or text. */
function textExpression(
  model: ComponentModel,
  node: UidxNode,
  scopes: readonly RepeatScope[] = [],
): string {
  const characters = node.attrs.characters?.value
  if (typeof characters !== 'string') return ''
  const prop = boundProp(model, characters)
  if (prop) return `{${prop.name}}`
  const path = boundPath(model, characters, scopes)
  if (path) {
    const [head, ...rest] = path
    return `{${head}${rest.map((segment) => `?.${segment}`).join('')}}`
  }
  return jsxText(characters)
}

/* ------------------------------------------------------------ the outer box */

/** `text` as a single-quoted JS string. */
function quoted(text: string): string {
  return `'${text.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`
}

/**
 * Declarations as a `style` value, `rest` spread last so it wins:
 * `{{ '--uidx-fill': 'var(--surface-danger)', width: '199px' } as CSSProperties}`.
 * `CSSProperties` names no custom property, so the object is asserted to it.
 */
function styleValue(style: Readonly<Record<string, string>>, rest?: string): string {
  const entries = Object.entries(style).map(
    ([prop, value]) => `${/^[A-Za-z]\w*$/.test(prop) ? prop : quoted(prop)}: ${quoted(value)}`,
  )
  if (rest !== undefined) entries.push(`...${rest}`)
  return `{{ ${entries.join(', ')} } as CSSProperties}`
}

/** A shorthand's hook and its longhands' hooks, found by any one of them. */
const HOOK_GROUPS = new Map(
  Object.entries(INSTANCE_BOX_SHORTHANDS).flatMap(([shorthand, longhands]) => {
    const group = {
      hook: INSTANCE_BOX_HOOKS[shorthand]!,
      longhands: longhands.map((longhand) => INSTANCE_BOX_HOOKS[longhand]!),
    }
    return [group.hook, ...group.longhands].map((hook) => [hook, group] as const)
  }),
)

/**
 * The hooks the instance a component hands its `style` to states, made to
 * give way to a shorthand the consumer's style states. On the canvas a use's
 * `cornerRadius` drops the corners the definition gave that instance (ADR
 * 0018 §5), and the HTML target drops them when it lays one over the other.
 * Here the consumer's side is known only at runtime, so the rule is put in
 * CSS: each longhand reads the shorthand's hook first, with its own value as
 * the fallback, and the component's root resets that hook unless the
 * consumer sets it. A shorthand stated beside its longhands is spelled out
 * into the ones it covers, so only the consumer's can take them all.
 */
function yielding(own: Readonly<Record<string, string>>): Record<string, string> {
  const out: Record<string, string> = {}
  for (const [hook, value] of Object.entries(own)) {
    const group = HOOK_GROUPS.get(hook)
    if (!group || !group.longhands.some((longhand) => longhand in own)) {
      out[hook] = value
      continue
    }
    // Spelled out once, where the group first appears.
    if (group.longhands.some((longhand) => longhand in out)) continue
    for (const longhand of group.longhands) {
      const stated = own[longhand] ?? own[group.hook]
      if (stated !== undefined) out[longhand] = `var(${group.hook}, ${stated})`
    }
  }
  return out
}

/**
 * `boxStyleOf`, written into a component whose element wraps the one
 * instance that is its box (ADR 0018 §2). The element keeps the consumer's
 * whole style, as a React root does: a margin, a flex share or a grid area
 * places the element. The box is handed its part: the `--uidx-*` hooks,
 * which its own root would otherwise reset, and a stated size, which it
 * fills — the canvas hands the held instance the use's size the same way.
 */
function boxStyleHelper(held: string): string[] {
  return [
    `/** The part of the consumer's style that belongs to the ${held} this holds: the --uidx-* hooks, and a size it fills. */`,
    'function boxStyleOf(style: CSSProperties | undefined): CSSProperties {',
    '  const box: Record<string, unknown> = {}',
    '  for (const [key, value] of Object.entries(style ?? {})) {',
    '    if (value === undefined) continue',
    "    if (key.startsWith('--uidx-')) box[key] = value",
    "    else if (key === 'width' || key === 'height') box[key] = '100%'",
    '  }',
    '  return box as CSSProperties',
    '}',
  ]
}

export function emitReact(model: ComponentModel, ctx: ReactContext): string {
  const contract = model.contract
  const props: PropLine[] = []
  const usesModels = new Set<string>()
  const imports = new Set<string>()
  const textBound = new Set<string>()

  // Which props are rendered as text somewhere: those accept a ReactNode.
  // Text the library draws inside a shadow part (outside any slot) is not
  // ours to render: when the element takes it as an attribute, it stays a
  // string prop passed through, as Shoelace's sl-input takes its label.
  const scanText = (node: UidxNode, shadowed: boolean): void => {
    const part = model.partOf.get(node)
    const kind =
      part === undefined ? undefined : model.parts.find((entry) => entry.name === part)?.kind
    const inShadow = node.element === 'Slot' ? false : shadowed || kind === 'shadow'
    const prop = boundProp(model, node.attrs.characters?.value ?? null)
    if (prop && node.element === 'Text') {
      const attribute = model.elementAttributes.has(attributeName(model, prop.name))
      if (!(inShadow && attribute)) textBound.add(prop.name)
    }
    for (const child of node.children) scanText(child, inShadow)
  }
  scanText(model.node, false)

  const attributeProps: PropSpec[] = []
  for (const prop of contract?.props ?? []) {
    const found = modelOfType(prop.type, model.spec, model.models)
    // A prop that receives a model is the component's input: required, and
    // its fields are what the parts bind (ADR 0015 §2).
    if (found && !found.list) {
      usesModels.add(pascal(found.model.name))
      props.push({
        name: prop.name,
        type: pascal(found.model.name),
        optional: false,
        doc: prop.description,
      })
      continue
    }
    const type = textBound.has(prop.name) ? 'ReactNode' : tsType(model, prop.type)
    if (found?.list) usesModels.add(pascal(found.model.name))
    // A list an element repeats over is what the component draws: required,
    // and not an attribute of the element (ADR 0017 §2).
    const repeated = model.repeats.some((repeat) => repeat.list === prop.name)
    props.push({ name: prop.name, type, optional: !repeated, doc: prop.description })
    if (!textBound.has(prop.name) && !repeated) attributeProps.push(prop)
  }
  for (const event of contract?.events ?? []) {
    const handler = `on${pascal(event.name)}`
    props.push({
      name: handler,
      type: `(detail: ${event.detail ?? 'unknown'}) => void`,
      optional: true,
      doc: event.description,
    })
  }
  for (const slot of model.slots) {
    // A repeating slot is a render prop, declared with its repeat below.
    if (model.repeats.some((repeat) => repeat.node === slot.node)) continue
    props.push({
      name: slot.name === 'default' ? 'children' : slot.name,
      type: 'ReactNode',
      optional: true,
      doc: slot.spec?.description ?? `Content of the "${slot.name}" slot.`,
    })
  }
  // A repeating slot (ADR 0017 §2) is a render prop named after the slot:
  // `renderOption(item, index)`; the slot's content is the default.
  for (const repeat of model.repeats) {
    if (repeat.model) usesModels.add(pascal(repeat.model.name))
    if (!repeat.fillable) continue
    const item = repeat.model ? pascal(repeat.model.name) : 'unknown'
    props.push({
      name: renderPropName(repeat),
      type: `(${repeat.as}: ${item}, index: number) => ReactNode`,
      optional: true,
      doc:
        repeat.slot?.description ?? `Draws one "${repeat.node.name}"; the design's is the default.`,
    })
  }
  const targetOf = (node: UidxNode): ComponentModel | undefined => {
    const name = node.attrs.component?.value
    return typeof name === 'string' ? ctx.components.get(name) : undefined
  }
  // The consumer's `style` carries the hooks (ADR 0018 §6), which act where a
  // use's outer box lands (§2): the root, or the one instance that is the
  // box. A composition renders as that instance, so it takes the style whole.
  // An element that wraps one keeps the style, since where it sits is its
  // own, as any React root's is, and hands the box the part that is the
  // box's (`boxStyleOf`) — unless the instance cannot take a style.
  const box = boxOf(model)
  const boxInstance = box.kind === 'instance' ? box.node : undefined
  const boxTarget = boxInstance && targetOf(boxInstance)
  const handsStyleOn =
    !model.composes && boxTarget !== undefined && !ctx.adapters?.has(boxTarget.name)
  props.push({
    name: 'className',
    type: 'string',
    optional: true,
    doc: 'Extra class names for the root element.',
  })
  props.push({
    name: 'style',
    type: 'CSSProperties',
    optional: true,
    doc: handsStyleOn
      ? `Inline style for the root element. Its --uidx-* hooks and its size also reach its box, the ${boxTarget!.name} it holds (ADR 0018 §2).`
      : 'Inline style for the root element.',
  })

  const compound: { name: string; tag: string; part: string }[] = []
  for (const part of model.parts) {
    const prop = boundProp(model, part.node.attrs.characters?.value ?? null)
    // A shadow part has no element to compose below the root.
    if (prop && part.node.element === 'Text' && part.kind === 'element')
      compound.push({ name: pascal(part.name), tag: part.tag, part: part.name })
  }

  /**
   * The style a use sets on the component it draws (ADR 0018 §6): the hooks
   * for the box and text colour it states, and the size it fixes, as the
   * HTML target writes them. An adapter takes the contract's props and
   * nothing else, so it gets none, and the generator hears of any hook lost.
   */
  const useStyle = (node: UidxNode, target: ComponentModel): Record<string, string> => {
    const style = instanceInlineStyle(node, target, parentOf(model, node)?.attrs.layoutMode?.value)
    const adapter = ctx.adapters?.get(target.name)
    if (!adapter) return style
    const lost = Object.keys(node.attrs).filter((prop) => {
      const hook = INSTANCE_BOX_HOOKS[prop]
      return hook !== undefined && hook in style
    })
    if (lost.length)
      ctx.warn?.(
        node,
        `"${node.name}" sets ${lost.join(', ')} on ${target.name}, which codegen.react renders ` +
          `onto ${adapter.from}: its adapter takes no --uidx-* hooks, so React draws the ` +
          "library's own look there (ADR 0018 §6)",
      )
    return {}
  }
  /**
   * For the instance that is the box: what the use states there, with what
   * the consumer's style hands it laid over — all of it for a composition,
   * which renders as that instance, or the box's part of it.
   */
  const handedStyle = (own: Record<string, string>, handed: string): string =>
    Object.keys(own).length ? styleValue(yielding(own), handed) : `{${handed}}`

  const rendering = new Set<UidxNode>()
  const render = (node: UidxNode, depth: number, scopes: RepeatScope[] = []): string[] => {
    const pad = '  '.repeat(depth)
    const part = model.partOf.get(node)
    const info = part === undefined ? undefined : model.parts.find((entry) => entry.name === part)
    // As in the HTML target: a shadow part is drawn by the library.
    if (info?.kind === 'shadow') return slotsWithin(node, (slot) => render(slot, depth, scopes))
    // ADR 0017 §2: an element with `repeat` maps over its list; the n-th row
    // binds `{as.field}` to the item. A repeating slot lets the consumer draw
    // the row instead, through its render prop.
    const repeat = repeatFor(model, node)
    if (repeat && !rendering.has(node)) {
      rendering.add(node)
      const key = repeat.model?.fields.find((field) => field.key)?.name
      const inner = [...scopes, { as: repeat.as, model: repeat.model }]
      const row =
        node.element === 'Slot'
          ? node.children.flatMap((child) => render(child, depth + 2, inner))
          : render(node, depth + 2, inner)
      rendering.delete(node)
      const body = row.length ? row : [`${pad}    null`]
      // One child is one element and needs no fragment around it; several do.
      const single = node.element === 'Slot' && node.children.length === 1 && row.length > 0
      return [
        `${pad}{${repeat.list}.map((${repeat.as}, index) => (`,
        `${pad}  <Fragment key={${key ? `String(${repeat.as}.${key})` : 'index'}}>`,
        ...(repeat.fillable
          ? [
              `${pad}    {${renderPropName(repeat)} ? ${renderPropName(repeat)}(${repeat.as}, index) : (`,
              ...(single
                ? body.map((line) => `  ${line}`)
                : [`${pad}      <>`, ...body.map((line) => `    ${line}`), `${pad}      </>`]),
              `${pad}    )}`,
            ]
          : body),
        `${pad}  </Fragment>`,
        `${pad}))}`,
      ]
    }
    const children = () => node.children.flatMap((child) => render(child, depth + 1, scopes))
    switch (node.element) {
      case 'Instance': {
        const target = targetOf(node)
        // The instance a composition renders as is its root (ADR 0012 §3):
        // the consumer's className and style go on it.
        const asRoot = node === model.composes
        if (!target)
          return [
            `${pad}<div${asRoot ? ' className={className} style={style}' : ''} data-instance="${String(node.attrs.component?.value ?? '')}" />`,
          ]
        imports.add(target.identifier)
        // A use passes props through (F7): `{label}` hands this component's
        // own prop down, a literal is a literal. A slot fill (ADR 0007 §2)
        // becomes the slot's ReactNode prop.
        const passed: string[] = []
        const declared = node.attrs.props?.value
        if (declared && typeof declared === 'object' && !Array.isArray(declared)) {
          for (const [key, value] of Object.entries(declared as Record<string, JsonValue>)) {
            const own = boundProp(model, value)
            const item = itemAlias(value, scopes)
            if (own) passed.push(`${key}={${own.name}}`)
            else if (item !== null) passed.push(`${key}={${item}}`)
            else if (typeof value === 'string' && !value.startsWith('{'))
              passed.push(`${key}="${value}"`)
            else if (typeof value !== 'string') passed.push(`${key}={${JSON.stringify(value)}}`)
          }
        }
        // The row's item reaches a nested component only as the use binds it
        // (`props={{ item: '{item}' }}`, ADR 0017 §2) — passed above like any
        // other bound prop. Nothing is inferred from types.

        // Its outer box and size go as `style` (ADR 0018 §6): its own, or —
        // where it is this component's box — the consumer's laid over it.
        const own = useStyle(node, target)
        const handed = asRoot || (node === boxInstance && handsStyleOn)
        const attributes = [
          ...(asRoot ? ['className={className}'] : []),
          ...(handed ? [`style=${handedStyle(own, asRoot ? 'style' : 'boxStyleOf(style)')}`] : []),
          ...passed,
          ...(!handed && Object.keys(own).length ? [`style=${styleValue(own)}`] : []),
        ]
        const open = `${pad}<${target.identifier}${attributes.length ? ` ${attributes.join(' ')}` : ''}`
        const fills = node.children.filter((child) => child.element === 'Slot')
        if (fills.length === 0) return [`${open} />`]
        const lines = [open]
        for (const fill of fills) {
          const prop = fill.name === 'default' ? 'children' : fill.name
          const inner = fill.children.flatMap((child) => render(child, depth + 2, scopes))
          lines.push(`${pad}  ${prop}={`, `${pad}    <>`, ...inner, `${pad}    </>`, `${pad}  }`)
        }
        lines.push(`${pad}/>`)
        return lines
      }
      case 'Slot': {
        const prop = node.name === 'default' ? 'children' : node.name
        const fallback = node.children.length ? children() : []
        const slot = model.slotted.has(node.name) ? ` slot="${node.name}"` : ''
        if (fallback.length) {
          return [
            `${pad}<span${slot} data-slot="${node.name}">`,
            `${pad}  {${prop} !== undefined ? ${prop} : (`,
            ...fallback.map((line) => `  ${line}`),
            `${pad}  )}`,
            `${pad}</span>`,
          ]
        }
        return [
          `${pad}{${prop} !== undefined ? <span${slot} data-slot="${node.name}">{${prop}}</span> : null}`,
        ]
      }
      case 'Text': {
        const text = textExpression(model, node, scopes)
        if (info) return [`${pad}<${info.tag}>${text}</${info.tag}>`]
        return [`${pad}<span data-node="${node.name}">${text}</span>`]
      }
      case 'Vector': {
        const svg = svgFor(node)
        if (info) return [`${pad}<${info.tag}>${svg}</${info.tag}>`]
        return [`${pad}<span data-node="${node.name}">${svg}</span>`]
      }
      default: {
        if (node === model.node) return children()
        if (info?.kind === 'data-part')
          return [`${pad}<span data-part="${info.libraryName}">`, ...children(), `${pad}</span>`]
        if (info) return [`${pad}<${info.tag}>`, ...children(), `${pad}</${info.tag}>`]
        return [`${pad}<div data-node="${node.name}">`, ...children(), `${pad}</div>`]
      }
    }
  }
  const rootTag = model.tag ?? 'div'
  // A composition renders as the instance it holds, className and style
  // handed to it, so the pattern adds no element of its own. Each use is
  // rendered once, so the generator hears of it once.
  const composed = model.composes ? render(model.composes, 2) : null
  const body = composed ? [] : render(model.node, 2)
  // Props reach the element the way the library reflects them (ADR 0013 §3):
  // as attributes, as data attributes, or as classes joined onto className.
  const classed = model.profile.props === 'class' ? attributeProps : []
  const attributes = (model.profile.props === 'class' ? [] : attributeProps)
    .map((prop) => {
      const isBoolean = prop.type === 'boolean'
      const name = attributeName(model, prop.name)
      const attr = model.profile.props === 'data-attribute' ? `data-${name}` : name
      // On a custom element React sets the property, and `undefined` does not
      // clear a reflected boolean in Lit — `disabled` would stick once on — so
      // the element gets a real boolean. Elsewhere `undefined` drops the
      // attribute rather than writing `"false"`.
      const flag = model.tag && attr === name ? `!!${prop.name}` : `${prop.name} || undefined`
      return `${attr}={${isBoolean ? flag : prop.name}}`
    })
    .join(' ')
  // The `empty` state (ADR 0017 §4) is the consumer's data, not a prop, so
  // the wrapper computes it from the lists it was handed.
  const lists = listProps(contract)
  const emptyAttr = lists.length
    ? `data-empty={(${lists.map((name) => `(${name}?.length ?? 0) === 0`).join(' && ')}) || undefined}`
    : ''
  const rootAttributes = [attributes, emptyAttr].filter(Boolean).join(' ')
  const classNameExpr = classed.length
    ? `{[${model.tag ? '' : `'${model.stem}', `}className, ${classed
        .map((prop) =>
          prop.type === 'boolean'
            ? `${prop.name} ? '${attributeName(model, prop.name)}' : undefined`
            : `${prop.name} !== undefined ? \`${attributeName(model, prop.name)}-\${${prop.name}}\` : undefined`,
        )
        .join(', ')}].filter(Boolean).join(' ')}`
    : model.tag
      ? '{className}'
      : // Without a tag the stylesheet's root is the component's class.
        `{['${model.stem}', className].filter(Boolean).join(' ')}`
  const events = (contract?.events ?? []).map(
    (event) => `  useElementEvent(ref, '${eventName(model, event.name)}', on${pascal(event.name)})`,
  )
  const destructure = props
    .map((prop) => {
      const fallback = contract?.props.find((entry) => entry.name === prop.name)?.default
      const isAttribute = attributeProps.some((entry) => entry.name === prop.name)
      return isAttribute &&
        fallback !== undefined &&
        fallback !== null &&
        typeof fallback !== 'boolean'
        ? `${prop.name} = ${JSON.stringify(fallback)}`
        : prop.name
    })
    .join(', ')

  const reactImports = [...(model.composes ? [] : ['useRef']), 'type CSSProperties']
  if (props.some((prop) => prop.type.includes('ReactNode')) || compound.length)
    reactImports.push('type ReactNode')
  if (model.repeats.length) reactImports.push('Fragment')
  const lines: string[] = [
    HEADER(model.name),
    `import { ${reactImports.sort().join(', ')} } from 'react'`,
    ...(contract?.events.length ? [`import { useElementEvent } from './runtime'`] : []),
    ...(usesModels.size
      ? [`import type { ${[...usesModels].sort().join(', ')} } from './models'`]
      : []),
    ...[...imports].sort().map((name) => `import { ${name} } from './${name}'`),
    `import './${model.stem}.css'`,
    '',
    `export interface ${model.identifier}Props {`,
    ...props.flatMap((prop) => [
      `  /** ${prop.doc} */`,
      `  ${prop.name}${prop.optional ? '?' : ''}: ${prop.type}`,
    ]),
    '}',
    '',
    ...(handsStyleOn ? [...boxStyleHelper(boxTarget!.name), ''] : []),
    `function ${model.identifier}Base({ ${destructure} }: ${model.identifier}Props) {`,
    ...(composed
      ? [`  return (`, ...composed, `  )`]
      : [
          `  const ref = useRef<${model.tag ? 'HTMLElement' : 'HTMLDivElement'}>(null)`,
          ...events,
          `  return (`,
          `    <${rootTag} ref={ref} className=${classNameExpr} style={style}${rootAttributes ? ` ${rootAttributes}` : ''}>`,
          ...body,
          `    </${rootTag}>`,
          `  )`,
        ]),
    `}`,
    '',
  ]
  for (const sub of compound) {
    lines.push(
      `function ${model.identifier}${sub.name}({ children }: { children?: ReactNode }) {`,
      `  return <${sub.tag}>{children}</${sub.tag}>`,
      `}`,
      '',
    )
  }
  if (compound.length) {
    lines.push(
      `/** ${model.name}: the pattern, and its parts for composing below it. */`,
      `export const ${model.identifier} = Object.assign(${model.identifier}Base, {`,
      ...compound.map((sub) => `  ${sub.name}: ${model.identifier}${sub.name},`),
      `})`,
    )
  } else {
    lines.push(`export const ${model.identifier} = ${model.identifier}Base`)
  }
  return `${lines.join('\n')}\n`
}
