import {
  aliasTarget,
  type FieldSpec,
  type JsonValue,
  type PropSpec,
  type UidxNode,
} from '@uidx/format'
import { modelOfType, type ModelIndex, type RepeatScope } from '@uidx/schema/design-system'
import {
  attributeName,
  boundPath,
  boundProp,
  eventName,
  pascal,
  repeatFor,
  type ComponentModel,
  type RepeatInfo,
} from './model.js'

/**
 * The React target (ADR 0017 §3): one component per identity, wrapping the
 * headless root. Props and events come from the contract; slots are the
 * render-prop answer — a plain slot is a `ReactNode` prop, a repeating slot
 * is `items` plus `renderItem` generic over the model; parts with consumer
 * text are compound sub-components. Behaviour and accessibility come from the
 * custom element at runtime; appearance from the generated stylesheet.
 */

export interface ReactContext {
  components: Map<string, ComponentModel>
}

const HEADER = (name: string) =>
  `// ${name} — generated by uidx codegen from its .uidx file. Do not edit; change the file.\n`

/** A contract type string as TypeScript, with model names resolved (ADR 0015 §2). */
export function tsType(model: ComponentModel, type: string | undefined): string {
  return typeAgainst(type, model.spec, model.models)
}

function typeAgainst(
  type: string | undefined,
  spec: ComponentModel['spec'],
  models: ModelIndex,
): string {
  if (!type) return 'unknown'
  const found = modelOfType(type, spec, models)
  if (found) return found.list ? `${pascal(found.model.name)}[]` : pascal(found.model.name)
  const array = type.endsWith('[]')
  const base = array ? type.slice(0, -2) : type
  const inner = base === 'image' || base === 'date' ? 'string' : base
  return array ? `${inner}[]` : inner
}

function fieldType(models: ModelIndex, field: FieldSpec): string {
  return typeAgainst(field.type, undefined, models)
}

/** `models.ts`: one interface per model, fields documented from the file. */
export function emitModels(models: ModelIndex): string {
  const lines = [HEADER('Models'), '']
  for (const model of models.values()) {
    if (model.description) lines.push(`/** ${model.description} */`)
    lines.push(`export interface ${pascal(model.name)} {`)
    for (const field of model.fields) {
      lines.push(`  /** ${field.description} */`)
      lines.push(`  ${field.name}${field.optional ? '?' : ''}: ${fieldType(models, field)}`)
    }
    lines.push('}', '')
  }
  return `${lines.join('\n')}\n`
}

/** `runtime.ts`: the one hook every generated component uses for events. */
export function emitRuntime(): string {
  return `${HEADER('Runtime')}
import { useEffect, type RefObject } from 'react'

/**
 * Subscribes to a custom element's event and hands the handler its detail.
 * The element owns the behaviour; React only listens.
 */
export function useElementEvent<T>(
  ref: RefObject<HTMLElement | null>,
  type: string,
  handler: ((detail: T) => void) | undefined,
): void {
  useEffect(() => {
    const element = ref.current
    if (!element || !handler) return
    const listener = (event: Event) => handler((event as CustomEvent<T>).detail)
    element.addEventListener(type, listener)
    return () => element.removeEventListener(type, listener)
  }, [ref, type, handler])
}
`
}

/** `elements.d.ts`: the custom elements as JSX intrinsics, attributes open. */
export function emitElementTypes(tags: readonly string[]): string {
  const entries = [...new Set(tags)]
    .sort()
    .map(
      (tag) =>
        `      '${tag}': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> &\n        Record<string, unknown>`,
    )
  return `${HEADER('Elements')}
import type React from 'react'

declare module 'react' {
  namespace JSX {
    interface IntrinsicElements {
${entries.join('\n')}
    }
  }
}

export {}
`
}

export function emitIndex(models: readonly ComponentModel[]): string {
  const lines = [HEADER('Index'), '']
  for (const model of models) lines.push(`export * from './${model.identifier}'`)
  lines.push(`export * from './models'`)
  return `${lines.join('\n')}\n`
}

/* --------------------------------------------------------------- one component */

interface PropLine {
  name: string
  type: string
  optional: boolean
  doc: string
}

function jsxText(text: string): string {
  return text.replace(/[{}<>]/g, (c) => `{'${c}'}`)
}

function svgFor(node: UidxNode): string {
  const width = typeof node.attrs.width?.value === 'number' ? node.attrs.width.value : 16
  const height = typeof node.attrs.height?.value === 'number' ? node.attrs.height.value : 16
  const paths = Array.isArray(node.attrs.vectorPaths?.value)
    ? (node.attrs.vectorPaths.value as JsonValue[])
    : []
  const d = paths
    .map((entry) =>
      entry && typeof entry === 'object' && !Array.isArray(entry)
        ? (entry as Record<string, JsonValue>).data
        : undefined,
    )
    .filter((data): data is string => typeof data === 'string')
  return `<svg viewBox="0 0 ${width} ${height}" width={${width}} height={${height}} aria-hidden="true">${d.map((data) => `<path d="${data}" fill="currentColor" />`).join('')}</svg>`
}

/** `renderOption` for a repeating slot named `option` (ADR 0017 §2). */
/** `{child}` or `{child.owner}` inside a repeat: the item, or a field of it, as a JS path. */
function itemAlias(value: JsonValue, scopes: readonly RepeatScope[]): string | null {
  if (typeof value !== 'string') return null
  const target = aliasTarget(value)
  if (target === null || target.includes('#')) return null
  const head = target.split('.')[0]!
  return scopes.some((scope) => scope.as === head) ? target : null
}

const renderPropName = (repeat: RepeatInfo): string => `render${pascal(repeat.node.name)}`

/** The JSX expression a bound `characters` renders: a prop, a model path, or text. */
function textExpression(
  model: ComponentModel,
  node: UidxNode,
  scopes: readonly RepeatScope[] = [],
): string {
  const characters = node.attrs.characters?.value
  if (typeof characters !== 'string') return ''
  const prop = boundProp(model, characters)
  if (prop) return `{${prop.name}}`
  const path = boundPath(model, characters, scopes)
  if (path) {
    const [head, ...rest] = path
    return `{${head}${rest.map((segment) => `?.${segment}`).join('')}}`
  }
  return jsxText(characters)
}

export function emitReact(model: ComponentModel, ctx: ReactContext): string {
  const contract = model.contract
  const props: PropLine[] = []
  const usesModels = new Set<string>()
  const imports = new Set<string>()
  const textBound = new Set<string>()

  // Which props are rendered as text somewhere: those accept a ReactNode.
  const scanText = (node: UidxNode): void => {
    const prop = boundProp(model, node.attrs.characters?.value ?? null)
    if (prop && node.element === 'Text') textBound.add(prop.name)
    for (const child of node.children) scanText(child)
  }
  scanText(model.node)

  const attributeProps: PropSpec[] = []
  for (const prop of contract?.props ?? []) {
    const found = modelOfType(prop.type, model.spec, model.models)
    // A prop that receives a model is the component's input: required, and
    // its fields are what the parts bind (ADR 0015 §2).
    if (found && !found.list) {
      usesModels.add(pascal(found.model.name))
      props.push({
        name: prop.name,
        type: pascal(found.model.name),
        optional: false,
        doc: prop.description,
      })
      continue
    }
    const type = textBound.has(prop.name) ? 'ReactNode' : tsType(model, prop.type)
    if (found?.list) usesModels.add(pascal(found.model.name))
    // A list an element repeats over is what the component draws: required,
    // and not an attribute of the element (ADR 0017 §2).
    const repeated = model.repeats.some((repeat) => repeat.list === prop.name)
    props.push({ name: prop.name, type, optional: !repeated, doc: prop.description })
    if (!textBound.has(prop.name) && !repeated) attributeProps.push(prop)
  }
  for (const event of contract?.events ?? []) {
    const handler = `on${pascal(event.name)}`
    props.push({
      name: handler,
      type: `(detail: ${event.detail ?? 'unknown'}) => void`,
      optional: true,
      doc: event.description,
    })
  }
  for (const slot of model.slots) {
    // A repeating slot is a render prop, declared with its repeat below.
    if (model.repeats.some((repeat) => repeat.node === slot.node)) continue
    props.push({
      name: slot.name === 'default' ? 'children' : slot.name,
      type: 'ReactNode',
      optional: true,
      doc: slot.spec?.description ?? `Content of the "${slot.name}" slot.`,
    })
  }
  // A repeating slot (ADR 0017 §2) is a render prop named after the slot:
  // `renderOption(item, index)`; the slot's content is the default.
  for (const repeat of model.repeats) {
    if (repeat.model) usesModels.add(pascal(repeat.model.name))
    if (!repeat.fillable) continue
    const item = repeat.model ? pascal(repeat.model.name) : 'unknown'
    props.push({
      name: renderPropName(repeat),
      type: `(${repeat.as}: ${item}, index: number) => ReactNode`,
      optional: true,
      doc:
        repeat.slot?.description ?? `Draws one "${repeat.node.name}"; the design's is the default.`,
    })
  }
  props.push({
    name: 'className',
    type: 'string',
    optional: true,
    doc: 'Extra class names for the root element.',
  })
  props.push({
    name: 'style',
    type: 'CSSProperties',
    optional: true,
    doc: 'Inline style for the root element.',
  })

  const compound: { name: string; tag: string; part: string }[] = []
  for (const part of model.parts) {
    const prop = boundProp(model, part.node.attrs.characters?.value ?? null)
    // A shadow part has no element to compose below the root.
    if (prop && part.node.element === 'Text' && part.kind === 'element')
      compound.push({ name: pascal(part.name), tag: part.tag, part: part.name })
  }

  const rendering = new Set<UidxNode>()
  const render = (node: UidxNode, depth: number, scopes: RepeatScope[] = []): string[] => {
    const pad = '  '.repeat(depth)
    const part = model.partOf.get(node)
    const info = part === undefined ? undefined : model.parts.find((entry) => entry.name === part)
    // As in the HTML target: a shadow part is drawn by the library.
    if (info?.kind === 'shadow') return []
    // ADR 0017 §2: an element with `repeat` maps over its list; the n-th row
    // binds `{as.field}` to the item. A repeating slot lets the consumer draw
    // the row instead, through its render prop.
    const repeat = repeatFor(model, node)
    if (repeat && !rendering.has(node)) {
      rendering.add(node)
      const key = repeat.model?.fields.find((field) => field.key)?.name
      const inner = [...scopes, { as: repeat.as, model: repeat.model }]
      const row =
        node.element === 'Slot'
          ? node.children.flatMap((child) => render(child, depth + 2, inner))
          : render(node, depth + 2, inner)
      rendering.delete(node)
      const body = row.length ? row : [`${pad}    null`]
      // One child is one element and needs no fragment around it; several do.
      const single = node.element === 'Slot' && node.children.length === 1 && row.length > 0
      return [
        `${pad}{${repeat.list}.map((${repeat.as}, index) => (`,
        `${pad}  <Fragment key={${key ? `String(${repeat.as}.${key})` : 'index'}}>`,
        ...(repeat.fillable
          ? [
              `${pad}    {${renderPropName(repeat)} ? ${renderPropName(repeat)}(${repeat.as}, index) : (`,
              ...(single
                ? body.map((line) => `  ${line}`)
                : [`${pad}      <>`, ...body.map((line) => `    ${line}`), `${pad}      </>`]),
              `${pad}    )}`,
            ]
          : body),
        `${pad}  </Fragment>`,
        `${pad}))}`,
      ]
    }
    const children = () => node.children.flatMap((child) => render(child, depth + 1, scopes))
    switch (node.element) {
      case 'Instance': {
        const name = node.attrs.component?.value
        const target = typeof name === 'string' ? ctx.components.get(name) : undefined
        if (!target) return [`${pad}<div data-instance="${String(name ?? '')}" />`]
        imports.add(target.identifier)
        // A use passes props through (F7): `{label}` hands this component's
        // own prop down, a literal is a literal. A slot fill (ADR 0007 §2)
        // becomes the slot's ReactNode prop.
        const passed: string[] = []
        const declared = node.attrs.props?.value
        if (declared && typeof declared === 'object' && !Array.isArray(declared)) {
          for (const [key, value] of Object.entries(declared as Record<string, JsonValue>)) {
            const own = boundProp(model, value)
            const item = itemAlias(value, scopes)
            if (own) passed.push(`${key}={${own.name}}`)
            else if (item !== null) passed.push(`${key}={${item}}`)
            else if (typeof value === 'string' && !value.startsWith('{'))
              passed.push(`${key}="${value}"`)
            else if (typeof value !== 'string') passed.push(`${key}={${JSON.stringify(value)}}`)
          }
        }
        // Inside a repeat, the row's item is what the instance is of (ADR 0017
        // §2): a prop typed by an enclosing item's model receives that item,
        // nearest first; failing a match by type, the target's first model
        // prop receives the innermost item. A use that passed one is left be.
        if (scopes.length) {
          const modelProps = (target.contract?.props ?? []).filter(
            (entry) => modelOfType(entry.type, target.spec, target.models)?.list === false,
          )
          for (const prop of modelProps) {
            if (passed.some((entry) => entry.startsWith(`${prop.name}=`))) continue
            const typed = [...scopes]
              .reverse()
              .find((scope) => scope.model?.name === prop.type.trim())
            const from = typed ?? (prop === modelProps[0] ? scopes[scopes.length - 1] : undefined)
            if (from) passed.push(`${prop.name}={${from.as}}`)
          }
        }
        const fills = node.children.filter((child) => child.element === 'Slot')
        if (fills.length === 0)
          return [`${pad}<${target.identifier}${passed.length ? ` ${passed.join(' ')}` : ''} />`]
        const lines = [`${pad}<${target.identifier}${passed.length ? ` ${passed.join(' ')}` : ''}`]
        for (const fill of fills) {
          const prop = fill.name === 'default' ? 'children' : fill.name
          const inner = fill.children.flatMap((child) => render(child, depth + 2, scopes))
          lines.push(`${pad}  ${prop}={`, `${pad}    <>`, ...inner, `${pad}    </>`, `${pad}  }`)
        }
        lines.push(`${pad}/>`)
        return lines
      }
      case 'Slot': {
        const prop = node.name === 'default' ? 'children' : node.name
        const fallback = node.children.length ? children() : []
        if (fallback.length) {
          return [
            `${pad}<span data-slot="${node.name}">`,
            `${pad}  {${prop} !== undefined ? ${prop} : (`,
            ...fallback.map((line) => `  ${line}`),
            `${pad}  )}`,
            `${pad}</span>`,
          ]
        }
        return [
          `${pad}{${prop} !== undefined ? <span data-slot="${node.name}">{${prop}}</span> : null}`,
        ]
      }
      case 'Text': {
        const text = textExpression(model, node, scopes)
        if (info) return [`${pad}<${info.tag}>${text}</${info.tag}>`]
        return [`${pad}<span data-node="${node.name}">${text}</span>`]
      }
      case 'Vector': {
        const svg = svgFor(node)
        if (info) return [`${pad}<${info.tag}>${svg}</${info.tag}>`]
        return [`${pad}<span data-node="${node.name}">${svg}</span>`]
      }
      default: {
        if (node === model.node) return children()
        if (info?.kind === 'data-part')
          return [`${pad}<span data-part="${info.libraryName}">`, ...children(), `${pad}</span>`]
        if (info) return [`${pad}<${info.tag}>`, ...children(), `${pad}</${info.tag}>`]
        return [`${pad}<div data-node="${node.name}">`, ...children(), `${pad}</div>`]
      }
    }
  }
  const body = render(model.node, 2)

  const rootTag = model.tag ?? 'div'
  // A composition renders as the instance it holds, className and style
  // handed to it, so the pattern adds no element of its own.
  const composed = model.composes ? render(model.composes, 2) : null
  // Props reach the element the way the library reflects them (ADR 0013 §3):
  // as attributes, as data attributes, or as classes joined onto className.
  const classed = model.profile.props === 'class' ? attributeProps : []
  const attributes = (model.profile.props === 'class' ? [] : attributeProps)
    .map((prop) => {
      const isBoolean = prop.type === 'boolean'
      const name = attributeName(model, prop.name)
      const attr = model.profile.props === 'data-attribute' ? `data-${name}` : name
      return `${attr}={${isBoolean ? `${prop.name} || undefined` : prop.name}}`
    })
    .join(' ')
  const classNameExpr = classed.length
    ? `{[className, ${classed
        .map((prop) =>
          prop.type === 'boolean'
            ? `${prop.name} ? '${attributeName(model, prop.name)}' : undefined`
            : `${prop.name} !== undefined ? \`${attributeName(model, prop.name)}-\${${prop.name}}\` : undefined`,
        )
        .join(', ')}].filter(Boolean).join(' ')}`
    : '{className}'
  const events = (contract?.events ?? []).map(
    (event) => `  useElementEvent(ref, '${eventName(model, event.name)}', on${pascal(event.name)})`,
  )
  const destructure = props
    .map((prop) => {
      const fallback = contract?.props.find((entry) => entry.name === prop.name)?.default
      const isAttribute = attributeProps.some((entry) => entry.name === prop.name)
      return isAttribute &&
        fallback !== undefined &&
        fallback !== null &&
        typeof fallback !== 'boolean'
        ? `${prop.name} = ${JSON.stringify(fallback)}`
        : prop.name
    })
    .join(', ')

  const reactImports = [...(model.composes ? [] : ['useRef']), 'type CSSProperties']
  if (props.some((prop) => prop.type.includes('ReactNode')) || compound.length)
    reactImports.push('type ReactNode')
  if (model.repeats.length) reactImports.push('Fragment')
  const lines: string[] = [
    HEADER(model.name),
    `import { ${reactImports.sort().join(', ')} } from 'react'`,
    ...(contract?.events.length ? [`import { useElementEvent } from './runtime'`] : []),
    ...(usesModels.size
      ? [`import type { ${[...usesModels].sort().join(', ')} } from './models'`]
      : []),
    ...[...imports].sort().map((name) => `import { ${name} } from './${name}'`),
    `import './${model.stem}.css'`,
    '',
    `export interface ${model.identifier}Props {`,
    ...props.flatMap((prop) => [
      `  /** ${prop.doc} */`,
      `  ${prop.name}${prop.optional ? '?' : ''}: ${prop.type}`,
    ]),
    '}',
    '',
    `function ${model.identifier}Base({ ${destructure} }: ${model.identifier}Props) {`,
    ...(composed
      ? [
          `  return (`,
          ...composed.map((line, at) =>
            at === 0 ? line.replace(/^(\s*<\w+)/, '$1 className={className} style={style}') : line,
          ),
          `  )`,
        ]
      : [
          `  const ref = useRef<HTMLElement>(null)`,
          ...events,
          `  return (`,
          `    <${rootTag} ref={ref} className=${classNameExpr} style={style}${attributes ? ` ${attributes}` : ''}>`,
          ...body,
          `    </${rootTag}>`,
          `  )`,
        ]),
    `}`,
    '',
  ]
  for (const sub of compound) {
    lines.push(
      `function ${model.identifier}${sub.name}({ children }: { children?: ReactNode }) {`,
      `  return <${sub.tag}>{children}</${sub.tag}>`,
      `}`,
      '',
    )
  }
  if (compound.length) {
    lines.push(
      `/** ${model.name}: the pattern, and its parts for composing below it. */`,
      `export const ${model.identifier} = Object.assign(${model.identifier}Base, {`,
      ...compound.map((sub) => `  ${sub.name}: ${model.identifier}${sub.name},`),
      `})`,
    )
  } else {
    lines.push(`export const ${model.identifier} = ${model.identifier}Base`)
  }
  return `${lines.join('\n')}\n`
}
