import { enumValues, type JsonValue, type ModelSpec, type PropSpec } from '@uidx/format'
import { modelOfType, sampleAt, type ModelIndex } from '@uidx/schema/design-system'

import type { ComponentModel } from './model.js'

/**
 * Storybook stories from an identity (ADR 0015 §3: "an example is exactly a
 * Storybook story or a visual regression fixture, and may be emitted as
 * one"). One CSF 3 file per React component: the default render with every
 * prop given its sample, one story per value of each visual prop, and one per
 * `## Examples` scene the args can express.
 *
 * Written beside the React target it imports, and like it a pure function of
 * the file. Storybook itself is the consumer's: the file only imports types
 * from `@storybook/react`.
 */
export function emitStories(model: ComponentModel, withTokens = false): string {
  const contract = model.contract
  const args: Record<string, JsonValue> = {}
  for (const prop of contract?.props ?? []) {
    const value = sampleArg(prop, model.models)
    if (value !== undefined) args[prop.name] = value
  }

  const stories: { name: string; args: Record<string, JsonValue> }[] = []
  const taken = new Set(['Default'])
  const add = (name: string, extra: Record<string, JsonValue>): void => {
    let unique = name
    for (let n = 2; taken.has(unique); n++) unique = `${name}${n}`
    taken.add(unique)
    stories.push({ name: unique, args: extra })
  }

  for (const prop of contract?.props ?? []) {
    if (!prop.visual) continue
    if (prop.type === 'boolean') {
      if (prop.default !== true) add(pascal(prop.name), { [prop.name]: true })
      continue
    }
    for (const value of enumValues(prop.type) ?? []) {
      if (value === prop.default) continue
      add(`${pascal(prop.name)}${pascal(value)}`, { [prop.name]: value })
    }
  }

  const declared = new Map((contract?.props ?? []).map((prop) => [prop.name, prop]))
  for (const example of model.spec?.examples ?? []) {
    const extra: Record<string, JsonValue> = {}
    for (const set of example.sets) {
      if (set.at === 'root' && set.state !== undefined) {
        const prop = declared.get(set.state)
        if (prop?.visual && prop.type === 'boolean') extra[set.state] = true
      } else if (set.at !== undefined && declared.has(set.at) && set.value !== undefined) {
        extra[set.at] = set.value
      } else if (set.slot !== undefined && set.count !== undefined) {
        // A count trims the list the repeating slot is filled from.
        const list = model.repeats.find((repeat) => repeat.node.name === set.slot)?.list
        const rows = list ? args[list] : undefined
        if (list && Array.isArray(rows)) extra[list] = rows.slice(0, set.count)
      }
    }
    add(`Example${pascal(example.name)}`, extra)
  }

  const lines = [
    `// ${model.name} — generated by uidx codegen from its .uidx file. Do not edit; change the file.`,
    '',
    `import type { Meta, StoryObj } from '@storybook/react'`,
    `import { ${model.identifier} } from './${model.identifier}'`,
    ...(withTokens ? [`import './tokens.css'`] : []),
    '',
    `const meta = {`,
    `  title: 'Design system/${model.name}',`,
    `  component: ${model.identifier},`,
    `  args: ${literal(args, 2)},`,
    `} satisfies Meta<typeof ${model.identifier}>`,
    '',
    `export default meta`,
    `type Story = StoryObj<typeof meta>`,
    '',
    `export const Default: Story = {}`,
  ]
  for (const story of stories) {
    const inline = Object.entries(story.args)
      .map(([key, value]) => `${key}: ${JSON.stringify(value)}`)
      .join(', ')
    lines.push('', `export const ${story.name}: Story = { args: { ${inline} } }`)
  }
  return `${lines.join('\n')}\n`
}

/** What a prop is given in the default story: its sample, its default, or its model's samples. */
function sampleArg(prop: PropSpec, models: ModelIndex): JsonValue | undefined {
  if (prop.sample !== undefined) return prop.sample
  if (prop.default !== undefined) return prop.default
  const found = modelOfType(prop.type?.trim(), undefined, models)
  if (!found) return undefined
  const rows = sampleRows(found.model, models, 0)
  return found.list ? rows : (rows[0] ?? null)
}

/** A model's sample rows: as many as its longest sample list, three when none is a list. */
export function sampleRows(
  model: ModelSpec,
  models: ModelIndex,
  depth: number,
): Record<string, JsonValue>[] {
  const count = Math.max(
    0,
    ...model.fields.map((field) => (Array.isArray(field.sample) ? field.sample.length : 0)),
  )
  const rows: Record<string, JsonValue>[] = []
  for (let index = 0; index < (count || 3); index++) {
    const row: Record<string, JsonValue> = {}
    for (const field of model.fields) {
      const nested = depth < 2 ? modelOfType(field.type.trim(), undefined, models) : undefined
      if (nested) {
        const inner = sampleRows(nested.model, models, depth + 1)
        row[field.name] = nested.list ? inner : (inner[0] ?? null)
        continue
      }
      const raw = Array.isArray(field.sample)
        ? field.sample[index % field.sample.length]
        : field.sample
      // An absent optional is left out, the way the adapter would omit it.
      if (raw === null && field.optional) continue
      const value = sampleAt(field, index)
      if (value !== undefined) row[field.name] = value
    }
    rows.push(row)
  }
  return rows
}

function pascal(text: string): string {
  return text
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((word) => word[0]!.toUpperCase() + word.slice(1))
    .join('')
}

/** A JSON value as a TypeScript literal, keys unquoted where they can be. */
function literal(value: JsonValue, indent: number): string {
  const json = JSON.stringify(value, null, 2)
  if (json === undefined) return 'undefined'
  return json
    .replace(/"([A-Za-z_$][\w$]*)":/g, '$1:')
    .split('\n')
    .map((line, at) => (at === 0 ? line : ' '.repeat(indent) + line))
    .join('\n')
}
